name: Deploy to GitHub Pages

on:
  # use [skip ci] in commit message to skip this workflow
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: Wu-Yijun/actions/.github/actions/deploy@main
        with:
          token: ${{ github.token }}  # 密钥, 默认使用 actions 自带的权限
          path: "dist/"               # 静态页面路径, 默认使用 dist 文件夹
          expire: 0.5                 # 文件暴露时间, 默认 0.5 秒(越长越稳定, 越短越安全)